apiVersion: v1
kind: Service
metadata:
  name: fernandapereira-recommender-service
spec:
  selector:
    app: fernandapereira-frontend
  ports:
    - protocol: TCP
      port: 32180
      targetPort: 32180
